### PR TITLE
Curve fitting in spectrometer modules

### PR DESCRIPTION
**Pull request by latchr**
## Description

The full Qudi curve fitting system has been added to spectrometer modules. The spectrum logic module now performs fits, and uses the same fit system as elsewhere (eg ODMR). Fit functions can be chosen from the list of implemented fits in fitlogic. The spectrometer GUI has been updated with a "fit" dockwidget that allows users to conviently choose a fit function and apply it to a specified domain. The resulting fit parameters are displayed in the GUI. An options menu with link to the fit settings dialog has been created. To cope with the increased complexity of the spectrometer gui, a "restore default view" method has been implemented.

## Motivation and Context

It is often useful to be able to extract properties of the spectrum (such as peak position or linewidth) in real-time while performing measurements. Standard fits make this easy to do.

## How Has This Been Tested?

Thorough testing using dummy hardware and the default config (updated in this branch). Also tested in laboratory with WinSpec hardware module.

## Screenshots (only if appropriate, delete if not):
spectrum_fit_eg

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [x] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by kay-jahnke** [comment]
@latchr Found a mean little bug:
In spectrum.py the new line 74 (``self._spectrum_data = np.zeros((2, 2))``) initializes the spectrum data inside the on_activate function. 
This overwrites the already initialized status variable and deletes the saved spectrum. So please delete line 74 from you code.

**Comment by latchr** [comment]
@drogenlied I believe the features/fixes you suggested are now implemented. Do I need to request a new review of this pull request, or do you just change your review?

@kay-jahnke good catch! I was having difficulty at first following the chain of initialising _spectrum_data and put line 74 in for my sanity. I've removed it and tested and it works both with and without an app_status folder.

**Comment by drogenlied** [comment]
@latchr no need for a new request, I can change the review  any time.

**Comment by drogenlied** [comment]
Looks way better now.

**Comment by kay-jahnke** [comment]
@latchr as you changed the default config, could you please write a short note on the announcement-channel (Dev should suffice, Jan can repost it on Announce).

**Comment by Neverhorst** [comment]
Guys, it would be nice if you could actually update `changelog.md` before merging (as stated in the pull request template check list).

**Pull request merged**
