### PR TITLE
Model/view for GUI

### PR DESCRIPTION
**Pull request by alrik-durand**
## Description
I've added a feature to easily link the state of a logic model to the state of a GUI view. I've also updated counter GUI to demonstrate how to use it.

## Motivation and Context
Adding just one spinbox in GUI and connecting it to logic can be a pain. Activation, deactivation, updating logic from GUI and GUI from logic all have to been done by hand at different part of the code. One usually use copy/paste a lot, never a good thing in a program !
Here the idea is to factor code by rendering explicit the concept of model and view.

Also the code of counter GUI needed some makeup !

## How Has This Been Tested?

I've tried testing as much as possible with counter GUI because adding abstraction can mess up things. I hope I have eliminated the last bug. This is tested on windows with dummies, no rpyc.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [x] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by Neverhorst** [comment]
Have you had a look at https://github.com/Ulm-IQO/qudi/blob/master/core/mapper.py ?

**Comment by alrik-durand** [comment]
No I did not know about that, but it looks very nice. Qudi will never cease to surprise me !

I guess I can close this PR, is it normal that no GUI module use this though ?

**Comment by Neverhorst** [comment]
From my personal chats with qudi programmers/users it seems like most people prefer to keep the full flexibility that Qt offers in signalling and event handling rather than committing to a fixed behaviour by using the mapper.

**Comment by alrik-durand** [comment]
I see why it is easier in some cases, I think some people (like me) were simply unaware of this feature. Are you ok if I try to implement it on at least one module as a showcase ? By doing this and adding something in the docs, maybe this nice feature would be used a bit more ?

**Comment by Neverhorst** [comment]
> I see why it is easier in some cases, I think some people (like me) were simply unaware of this feature. Are you ok if I try to implement it on at least one module as a showcase ? By doing this and adding something in the docs, maybe this nice feature would be used a bit more ?

Sure

**Comment by alrik-durand** [comment]
Ok, I'll close this one and open a new one for what we discussed.

**Pull request closed without merging**
