### PR TITLE
Desktop shortcut and some new documentation 

### PR DESCRIPTION
**Pull request by alrik-durand**
## Description
I've added a _logo_qudi.ico_ to the _artwork/logo_ folder to help making a nice desktop shortcut on windows with the appropriate explanation in the installation guide.
I've also added some context to the explanation guide to help newcomers understand why install Qudi the proper way.

## Motivation and Context
This change makes having a simple user friendly shortcut desktop on windows easier.

## How Has This Been Tested?
I've used this to make a shortcut and it works great. I haven't change Qudi's main code so I haven't  tested this any other way.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by a-stark** [comment]
@kay-jahnke, @alrik-durand, the merge was slightly to fast, I encountered some small things, which needed to be changed. But first of all thanks for the documentation!

Could you update the file `documentation/installation.md`: 
The file `documentation/required_python_package.md` was changed to `documentation/manual-package-installation.md` (i.e. the reference is different).

Can you tell me what the characters `&#65120;&#65120;` are doing in the shortcut? I tried to create it, but it was not working for me.


> Qudi is made in Python 3. A approachable and powerful programming language that is or soon will be the main languages of the physicists.

I really like this statement :D

**Comment by kay-jahnke** [comment]
Sorry for that.
As I can't revert master, can you fix it here in this branch, and than we just merge it again.

On another note: how do I reopen a branch?

**Comment by alrik-durand** [comment]
documentation/installation.md has been changed
The string windows want has two "&" in it but I encountered problems because PyCharm printed two black squares instead (& is used to include special caracters) so I used &#65120; because it correspond to a "&".

**Comment by alrik-durand** [comment]
Apparently it's not possible to reopen a closed pull request so I've open another one (I know this is very dirty !!!)

**Pull request merged**
