### PR TITLE
Hardware codes for additional fastcounter - the HydraHarp400 from PicoQuant

### PR DESCRIPTION
**Pull request by liuyanulm**
This update includes one more type of fastcounter, HydraHarp400 from PicoQuant
## Description

Composition of the hardware file for the new machine, basing on the requirements from fastcounter interface function list.
## Motivation and Context

Firstly, need to point out that the old hardware of PicoHarp300 has been out of time. It won't work under current Qudi, since the pulsed measurement has been updated quite some time ago. 
With the new machine HydraHarp 400, the function library of PicoQuant provided some updates too. The hardware file is composed accordingly.
## How Has This Been Tested?

Tested on a HydraHarp 400 machine connected to PC with USB. All functions in the file were tested to be fine.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [ x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ x] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by Neverhorst** [comment]
Well I guess that's a copyright infringement. All proprietary code will be purged from the repository history within the next days.

**Comment by liuyanulm** [comment]
> Well I guess that's a copyright infringement. All proprietary code will be purged from the repository history within the next days.

Why do you think this is a copyright infringement? Florian and I composed the code while we are in Shanghai.

**Comment by Neverhorst** [comment]
Because you committed proprietary code from _PicoQuant_ (the header files) and they explicitly forbid unauthorized distribution of their code.

**Comment by liuyanulm** [comment]
Thank you Niko for the explanation. I will make another PR containing only the hardware file without the header files. Would that be fine?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Neverhorst** [comment]
A PR with only `changelog.md` and `hharp400.py` files changed should be fine.

**Pull request closed without merging**
