### PR TITLE
Qt5 migration

### PR DESCRIPTION
**Pull request by latchr**
We have a problem because there is non-qt5 development occurring in this branch.  This makes it increasingly difficult for other development branches to stay up-to-date with the current state-of-the-art.  If the qt5 work is now complete then we need to merge this branch and shift unrelated development to other properly named branches.

I have successfully tested qt5-migration and I think I was the only one still having problems.  It seems we are now ready to merge this back to master, and it will bring the fit_overhaul work along with it.

### CODE REVIEW

**Comment by drogenlied** [comment]
As far as I can see, magnet logic and magnet GUI still need some fixing:

```
Error during activation
Traceback (most recent call last):
  File "/home/jan/qo/qudi/core/base.py", line 152, in _wrap_activation
    self.activate()
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 300, in fn
    self.transition()
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 295, in _tran
    self._after_event(e)
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 326, in _after_event
    return getattr(self, fnname)(e)
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 89, in _callback
    return func(obj, *args, **kwargs)
  File "/home/jan/qo/qudi/logic/magnet_logic.py", line 360, in on_activate
    self.odmr_2d_low_fitfunction = self.odmr_2d_low_fitfunction_list[1]
TypeError: 'odict_keys' object does not support indexing
```

```
Error during activation
Traceback (most recent call last):
  File "/home/jan/qo/qudi/core/base.py", line 152, in _wrap_activation
    self.activate()
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 300, in fn
    self.transition()
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 295, in _tran
    self._after_event(e)
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 326, in _after_event
    return getattr(self, fnname)(e)
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 89, in _callback
    return func(obj, *args, **kwargs)
  File "/home/jan/qo/qudi/gui/magnet/magnet_gui.py", line 413, in on_activate
    self._mw.align_2d_axes1_range_DSpinBox.valueChanged.connect(self.update_roi_from_range)
AttributeError: 'MagnetMainWindow' object has no attribute 'align_2d_axes1_range_DSpinBox'
```

```
Error during activation:
Traceback (most recent call last):
  File "/home/jan/qo/qudi/core/base.py", line 162, in _wrap_deactivation
    self.deactivate()
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 300, in fn
    self.transition()
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 295, in _tran
    self._after_event(e)
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 326, in _after_event
    return getattr(self, fnname)(e)
  File "/usr/lib/python3/dist-packages/fysom/__init__.py", line 89, in _callback
    return func(obj, *args, **kwargs)
  File "/home/jan/qo/qudi/logic/magnet_logic.py", line 499, in on_deactivate
    self._statusVariables['odmr_2d_low_fitfunction'] =  self.odmr_2d_low_fitfunction
  File "/home/jan/qo/qudi/core/base.py", line 138, in __getattr__
    return Fysom.__getattr__(self, name)
  File "/home/jan/qo/qudi/core/FysomAdapter.py", line 36, in __getattr__
    self.__class__, name))
AttributeError: '<class 'logic.magnet_logic.MagnetLogic'>' object has no attribute 'odmr_2d_low_fitfunction'
```

**Comment by latchr** [comment]
The problems in magnet logic and magnet gui are now fixed.  Does that mean that no obvious problems remain?

**Comment by Neverhorst** [comment]
Well I would not say that. I still get a lot of warnings in various situations coming from Qt when opening/closing windows. Maybe that's not a problem but it indicates that something is not working as intended under pyqt5. 
I think nobody really tested this branch for a couple of weeks in his setup. What held me off in doing so was the simply not useable changes to the fitting. And regarding that there is still no clear protocol how a fit should look like... it just works somehow in most cases. The different modules containing the fit methods still look highly heterogeneous. I also get NameErrors when using lorentzian fits related to this "sigma" parameter. we should tackle that first then test the branch for a couple of weeks and THEN merge. Otherwise i will be busy for the next month with fixing other people's setup.

**Comment by latchr** [comment]
Ah, that sounds different from the decision made at the last software meeting (where it was decided to merge fit_overhaul into qt5-migration in preparation for merging both into master).  However, I'm happy to slow down and hold both off until they are more tested.

Here's what I think we have to do.

1. We need to make sure that the qt5-migration branch is *only* used for developing/fixing things related to qt5 migration.  Anything else (fit fixes, connector issues, etc) need to be done elsewhere.  They can of course be merged into qt5-migration, but it is essential that people can benefit from these improvements *without* needing to use the qt5-migration branch.

2. Fit fixes should continue to be done in the fit_overhaul branch.  @Neverhorst can you please expand your claim that "there is no clear protocol how a fit should look like"?  Is this a documentation problem?  When I last checked I thought that the fitmethods files had been brought into a consistent pattern and design.  The new fit system works fine in ODMR, where is the problem occurring? I'm guessing it might be in pulsed, but @Neverhorst it is probably worth creating some specific issues.

3. We need to find people to test the qt5-migration branch.  This is fairly easy to do using the following steps.
  a) git checkout qt5-migration
  b) install the conda environment from tools/conda-env-<relevant OS>.yml  This is updated from the one in master, and will make sure you have the right qt versions and packages to talk to qt5.  If you want, you can even edit this yml file to make a new conda env with a name other than "qudi".  This makes it even easier to switch back to the qt4 branches.
  c) Load and test Qudi as usual.
  d) It is complicated by the fact that the fit_overhaul is merged into qt5-migration.  When you find bugs, try to work out whether it is a problem with fit or problem with qt5.

**Pull request merged**
