### PR TITLE
Predefined methods bugfix

### PR DESCRIPTION
**Pull request by Geegee**
The following generate methods have changed:

Ramsey, hahnecho, hahnecho_exp, xy8_tau, xy8_freq.
## Description

The changes fall into two categories:
    i) In the case that some or all tau values would lead to
       overlapping pulses the minimal tau is adjusted.
       For hanecho_exp as well as xy8_freq, the minimum tau is
       adjusted and the step size, for all others only the
       minimum tau is adjusted leading to a larger final tau.
    2) In the XY8 methods the tau half free evolution elements
       do not consider the different time between the center  of consecutive pulses i.e. (pi / 2, pi) vs. (pi, pi)
       vs. (pi, 3pi / 2)
## Motivation and Context

Choosing wrong free evolution for the $\frac{\tau}{2}$ elements in xy8 type measurements.
Generate methods behave more predictable (no points are recorded twice without notice)
Avoiding measuring points twice. 

## How Has This Been Tested?

Generating waveforms for all the methods with analog, not analog, alternating and non alternating 
settings. Checking for each the interpulse spacing and pulse lengths. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [ ] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by timoML** [comment]
For the general audience, here's what @Geegee and me discussed:
- put the logic for converting and checking taus into a seperate helper method 
- this PR would change the definition of taus in HE and Ramsey from "pulse spacing between MW" to "time between centers of MW pulses" (just like it's already defined in generate_xy8()). While we think this is more reasonable, we should discuss how to release and document this change.

**Comment by Neverhorst** [comment]
@timoML @Geegee Is this PR still valid after our discussions regarding the definition of inter-pulse spacings?

**Comment by timoML** [comment]
This PR will be replaced by some upcoming one based on the advancedsequences branch. Can be closed from my side.

**Comment by timoML** [comment]
This should have become obsolte with the warnings introduced in #650. @Geegee: Can you confirm, then we can close?

**Comment by Geegee** [comment]
Yes can be closed now.

**Pull request closed without merging**
