### PR TITLE
update

### PR DESCRIPTION
**Pull request by SimonSchmitt88**
Added a few methods and implemented the return of elaspsed sweep 

## Motivation and Context

Update

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by kay-jahnke** [comment]
In the function get_data, why do you first get the runtime but then return a value of None?

**Comment by SimonSchmitt88** [comment]
Thanks for reviewing @kay-jahnke. This time is the running time of the fastcomtec and not the running time of the experiment. Depending on the loading duration of the pulser there can be a minutes difference. After noticing that, I changed the return value to None.

**Comment by Neverhorst** [comment]
@SimonSchmitt88: Would it help to change pulsed measurements to always start the pulser before starting the counter?

**Comment by Neverhorst** [comment]
What's the status here, @SimonSchmitt88, @kay-jahnke, @NicolasStaudenmaier, @MathiasMetsch?
Is this branch even in use on some setup or has it become obsolete and another solution has emerged?

**Comment by SimonSchmitt88** [comment]
I don't think that this branch is in use at the moment. I close this PR and will have a look if it is worth to create a new PR soon.

**Pull request closed without merging**
