### PR TITLE
No or analogue laser channels

### PR DESCRIPTION
**Pull request by kay-jahnke**
Adding a laser on marker to the generated pulse block elements. This is necessary to have an empty or analogue laser channel.

## Description

Added a property to the PulseBlockElement, that determines if the laser is on in this element.
If the laser channel is analogue or empty, this property will be used to define the laser pulses, otherwise the determination will still be done via the digital channels.
Added a selection to the Gui and the predefined methods to set the new property.
Also had to add the empty channel to the allowed channel sets.

## Motivation and Context

There are szenarios, where no digital laser channel is set, but rather applied via flag (no laser channel) or an analogue voltage (digital laser channels).

## How Has This Been Tested?

So far only on dummy, this PR is for discussing if the technique works this way.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have documented my changes in the changelog (`documentation/changelog.md`)
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [x] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by kay-jahnke** [comment]
@Neverhorst This PR is to discuss if my idea works in principle.
I will have to fine tune the GUI and documentation, once I get an approval.

**Comment by Neverhorst** [comment]
Please also consider all the automated determination of laser length etc. For example the extraction method `ungated_gated_conv_deriv` assumes digital laser channels.

**Comment by Neverhorst** [comment]
> The activation config cannot be changed in the settings dialog.
> `set_pulse_generator_settings(...)` fails because the unions in `self.pulse_generator_constraints.activation_config` do not contain the empty channel, while the new `set_config` does and then you get the error message `Something went wrong while setting new activation config.` on line 350 of sequence_generator_logic.py

Could you please give the details on how this can be reproduced? Do I need this branch or is that an issue on master as well?

**Comment by tunden** [comment]
Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Nikolas Tomek <notifications@github.com> Datum: 01.02.19  16:54  (GMT+01:00) An: Ulm-IQO/qudi <qudi@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [Ulm-IQO/qudi] No or analogue laser channels (#473) 

The activation config cannot be changed in the settings dialog.

set_pulse_generator_settings(...) fails because the unions in self.pulse_generator_constraints.activation_config do not contain the empty channel, while the new set_config does and then you get the error message Something went wrong while setting new activation config. on line 350 of sequence_generator_logic.py

Could you please give the details on how this can be reproduced? Do I need this branch or is that an issue on master as well?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ulm-IQO/qudi","title":"Ulm-IQO/qudi","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Ulm-IQO/qudi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Neverhorst in #473: \u003e The activation config cannot be changed in the settings dialog.\r\n\u003e `set_pulse_generator_settings(...)` fails because the unions in `self.pulse_generator_constraints.activation_config` do not contain the empty channel, while the new `set_config` does and then you get the error message `Something went wrong while setting new activation config.` on line 350 of sequence_generator_logic.py\r\n\r\nCould you please give the details on how this can be reproduced? Do I need this branch or is that an issue on master as well?"}],"action":{"name":"View Pull Request","url":"https://github.com/Ulm-IQO/qudi/pull/473#issuecomment-459769080"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ulm-IQO/qudi/pull/473#issuecomment-459769080",
"url": "https://github.com/Ulm-IQO/qudi/pull/473#issuecomment-459769080",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by drogenlied** [comment]
This branch of course, just start a dummy config, generate a block/ensemble and try changing the channel activation.
Alternatively, try loading a generated block.

**Comment by Neverhorst** [comment]
The problem lies within `SequenceGeneratorLogic._apply_activation_config`.
As a return value you take the union of the `set_config` set with a set containing an empty string `{''}`.
This causes the returned set to always contain an empty string which is quite meaningless and causing the error. Simply return `set_config` as it is in the end.

**Comment by kay-jahnke** [comment]
Fixed it as to your suggestion, should be fine now.

**Comment by kay-jahnke** [comment]
As per request, also added the bins from the digital laser channel to the laser bins in case a digital laser channel is selected.

**Comment by kay-jahnke** [comment]
@Neverhorst please check again for chained readout pulses in gated counting.

**Pull request merged**
