### PR TITLE
Fix the installation procedure in windows

### LINKED ISSUE #360: install-python-modules-windows.bat fails on Windows 10
## *What* is affected by this bug?
New qudi conda environments are unable to be created on Windows 10 by running ```install-python-modules-windows.bat```. This is true for both 32-bit and 64-bit Windows 10 PCs.

## *When* does this occur?
When a user attempts to run ```install-python-modules-windows.bat``` from the command line an error occures (see below).

## *Where* on the platform does it happen?
The error generated is:
```
EnvironmentLocationNotFound: Not a conda environment
```

## *How* do we replicate the issue?
Run ```install-python-modules-windows.bat``` on 32-bit or 64-bit Windows 10.

## Expected behavior (i.e. solution)
I get around this problem by simply entering the last command in ```install-python-modules-windows.bat``` to create the environment:
```
conda env create -f conda-env-win8-qt5.yml
```

## Screenshot
img_20180405_150409

### PR DESCRIPTION
**Pull request by a-stark**
## Description

Adaptation of the installation script for windows. 
The batch script cannot handle exceptions in windows, therefore run within the batch script the installation procedure in windows powershell to be able to catch occurring exceptions (e.g. if conda environment "qudi" not present and you want to remove it).

**Edit:**
The windows installation script can handle now various windows versions (Windows 7, 8, 8.1 and 10) and the architecture for 32bit and 64bit.
Separate conda environments are added for Windows 7 32bit, Windows 7 64bit, and Windows 10 64bit

## Motivation and Context

The installation procedure of the conda environment in windows for qudi was broken. This pull request should fix #360.

## How Has This Been Tested?

Tested on Windows 10, Version 1803 (Build 17134.112)

**Edit:** 
Tested on Windows 7, 32bit.
Tested on Windows 7, 64bit with confocal capabilities

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [x] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by a-stark** [comment]
I extended the windows installation script by including different conda environments for the specific windows versions (currently we have conda environments for Windows 7 32bit, Windows 8, Windows 10 64bit. For all the other conda environments Windows 8 is taken to be the default one).
Now we have the possibility to provide specific conda environments which depend on the specific windows version. 
Maybe I can test it here with a windows 7 64bit. Then we would have already a lot of scenarios covered.

**Comment by a-stark** [comment]
More systems I do not have for testing, the installation script works and was tested on Windows 7 32bit, Windows 7 64bit and Windows 10. No error now in resolving the packages for the environment.
It might be good if someone else could test it, at least just the installation.

**Comment by drogenlied** [comment]
All of the new conda environments are missing the `lxml` package that is needed by `samples_write_methods` / `sequence_generator_logic.`

**Comment by kay-jahnke** [comment]
Apart from the error Jan mentioned everything works for me: Win7 64x

**Comment by a-stark** [comment]
Thanks for the test and the suggestions, I added the lxml package to all environments. I updated also the former `required_python_packages.md` documentation file and renamed it to `manual-package-installation.md`. Here I noted down, how to create manually a python environment (this is helpful to procude the *.yml files for a specific operating system). I think that the required package table is not useful to us (since it has changed anyway and will be sometimes specific for the selected OS), therefore I removed it.

**Comment by a-stark** [comment]
Oh boy, thanks a lot @kay-jahnke, the name has indeed skipped my checks.

**Comment by a-stark** [comment]
Apparently, I do not have write access to the repo to do the merge of the pull request?  Could you comment on that @drogenlied?

**Comment by drogenlied** [comment]
Try again, I changed some permissions after Lachlan directly pushed some commit to master.
Apparently it is not possible to allow people to merge, but not to push directly.

**Comment by a-stark** [comment]
wow, really? If I read the [Repository permission levels](https://help.github.com/articles/repository-permission-levels-for-an-organization/)) correctly, then a push to a protected branch is not allowed (which I think is good to prevent accidental push to master). I think it is still odd, that you cannot select user-based permissions on github...

**Pull request merged**
