### PR TITLE
TektronixAWG70k Minor sorting fix

### PR DESCRIPTION
**Pull request by alastair-marshall**
## Description
The new natural sort function doesn't work in two cases that I've found and so I've reverted these to use sorted instead. 

## Motivation and Context
This solves a problem with the AWG not functioning properly.
The error arose, because in these two cases the AWG7k is working with ints of the of the channel numbers and the natural sort in made for strings.

## How Has This Been Tested?
I'm running the latest version of qudi on my setup and found this issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by kay-jahnke** [comment]
this is now also fixed by #533. Do we still need this PR?

**Comment by alastair-marshall** [comment]
I think not, is #533 on qudi-master?

**Comment by kay-jahnke** [comment]
now it is.

**Comment by Neverhorst** [comment]
I would still like to merge this PR. Since you want to sort a list of integers it does not make sense to call `natural_sort`.

**Comment by kay-jahnke** [comment]
OK, @alastair-marshall can you add the changelog

**Comment by alastair-marshall** [comment]
In the process of adding it just now

**Pull request merged**
