### PR TITLE
Chirp pulses

### PR DESCRIPTION
**Pull request by jochen-scheuer**
Adding chirped ODMR with two different types of chirps. First a linear chirp and a Allen-Eberly chirp pulse.

## Description

Adding sampling functions and predefined methods for a chirped ODMR measurement.

## Motivation and Context

Adding more functionality.

## How Has This Been Tested?

Tested on setup 2 in IQO. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by liuyanulm** [comment]
I have run some test with this branch.
Here are some bugs I experienced:
When exiting Qudi on this branch, there are error reports: 
OrderedDict([('activation_config', frozenset({'d_ch2', 'a_ch2', 'd_ch3', 'd_ch1', 'a_ch1', 'd_ch4'}))])
Traceback (most recent call last):
  File "C:\qudi_odmr_cal\core\manager.py", line 1296, in saveStatusVariables
    config.save(filename, variables)
  File "C:\qudi_odmr_cal\core\config.py", line 231, in save
    default_flow_style=False)
  File "C:\qudi_odmr_cal\core\config.py", line 208, in ordered_dump
    return yaml.dump(data, stream, OrderedDumper, **kwds)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\main.py", line 849, in dump
    version=version, tags=tags, block_seq_indent=block_seq_indent)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\main.py", line 810, in dump_all
    dumper._representer.represent(data)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 73, in represent
    node = self.represent_data(data)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 101, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "C:\qudi_odmr_cal\core\config.py", line 155, in represent_ordereddict
    dict_data.items())
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 206, in represent_mapping
    node_value = self.represent_data(item_value)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 111, in represent_data
    node = self.yaml_representers[None](self, data)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 375, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
ruamel.yaml.representer.RepresenterError: cannot represent an object: frozenset({'d_ch2', 'a_ch2', 'd_ch3', 'd_ch1', 'a_ch1', 'd_ch4'})
Scanning Device will be reset.
Closing windows...
Stopping threads...

The "predefined method" got paralyzed, when I rolled back to master or other branches, with error reports:
Error during activation
Traceback (most recent call last):
  File "C:\qudi_odmr_cal\core\module.py", line 339, in wrap_event
    base_event(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\fysom\__init__.py", line 311, in fn
    self.transition()
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\fysom\__init__.py", line 306, in _tran
    self._after_event(e)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\fysom\__init__.py", line 338, in _after_event
    return getattr(self, fnname)(e)
  File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\fysom\__init__.py", line 95, in _callback
    return func(obj, *args, **kwargs)
  File "C:\qudi_odmr_cal\core\module.py", line 462, in __load_status_vars_activate
    self.on_activate()
  File "C:\qudi_odmr_cal\logic\pulsed\sequence_generator_logic.py", line 195, in on_activate
    self._update_blocks_from_file()
  File "C:\qudi_odmr_cal\logic\pulsed\sequence_generator_logic.py", line 778, in _update_blocks_from_file
    block = self._load_block_from_file(block_name)
  File "C:\qudi_odmr_cal\logic\pulsed\sequence_generator_logic.py", line 756, in _load_block_from_file
    block = pickle.load(file)
AttributeError: Can't get attribute 'AllenEberlyChirp' on <module 'basic_sampling_functions' from 'C:\\qudi_odmr_cal\\logic\\pulsed\\sampling_function_defs\\basic_sampling_functions.py'>

**Comment by liuyanulm** [comment]
> I have run some test with this branch.
> Here are some bugs I experienced:
> When exiting Qudi on this branch, there are error reports:
> OrderedDict([('activation_config', frozenset({'d_ch2', 'a_ch2', 'd_ch3', 'd_ch1', 'a_ch1', 'd_ch4'}))])
> Traceback (most recent call last):
> File "C:\qudi_odmr_cal\core\manager.py", line 1296, in saveStatusVariables
> config.save(filename, variables)
> File "C:\qudi_odmr_cal\core\config.py", line 231, in save
> default_flow_style=False)
> File "C:\qudi_odmr_cal\core\config.py", line 208, in ordered_dump
> return yaml.dump(data, stream, OrderedDumper, **kwds)
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\main.py", line 849, in dump
> version=version, tags=tags, block_seq_indent=block_seq_indent)
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\main.py", line 810, in dump_all
> dumper._representer.represent(data)
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 73, in represent
> node = self.represent_data(data)
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 101, in represent_data
> node = self.yaml_representers[data_types[0]](self, data)
> File "C:\qudi_odmr_cal\core\config.py", line 155, in represent_ordereddict
> dict_data.items())
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 206, in represent_mapping
> node_value = self.represent_data(item_value)
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 111, in represent_data
> node = self.yaml_representers[None](self, data)
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\ruamel\yaml\representer.py", line 375, in represent_undefined
> raise RepresenterError("cannot represent an object: %s" % data)
> ruamel.yaml.representer.RepresenterError: cannot represent an object: frozenset({'d_ch2', 'a_ch2', 'd_ch3', 'd_ch1', 'a_ch1', 'd_ch4'})
> Scanning Device will be reset.
> Closing windows...
> Stopping threads...
> 
> The "predefined method" got paralyzed, when I rolled back to master or other branches, with error reports:
> Error during activation
> Traceback (most recent call last):
> File "C:\qudi_odmr_cal\core\module.py", line 339, in wrap_event
> base_event(*args, **kwargs)
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\fysom__init__.py", line 311, in fn
> self.transition()
> File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\fysom__init__.py", line 306, in _tran
> self._after_event(e) File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\fysom__init__.py", line 338, in _after_event return getattr(self, fnname)(e) File "C:\ProgramData\Anaconda3\envs\qudi\lib\site-packages\fysom__init__.py", line 95, in _callback
> return func(obj, *args, **kwargs)
> File "C:\qudi_odmr_cal\core\module.py", line 462, in __load_status_vars_activate
> self.on_activate()
> File "C:\qudi_odmr_cal\logic\pulsed\sequence_generator_logic.py", line 195, in on_activate
> self._update_blocks_from_file()
> File "C:\qudi_odmr_cal\logic\pulsed\sequence_generator_logic.py", line 778, in _update_blocks_from_file
> block = self._load_block_from_file(block_name)
> File "C:\qudi_odmr_cal\logic\pulsed\sequence_generator_logic.py", line 756, in _load_block_from_file
> block = pickle.load(file)
> AttributeError: Can't get attribute 'AllenEberlyChirp' on <module 'basic_sampling_functions' from 'C:\qudi_odmr_cal\logic\pulsed\sampling_function_defs\basic_sampling_functions.py'>

I figured out the problem. this is caused by restoration of pulse blocks and ensembles.

Solution:
Roll back to 'Chirp pulses' branch, and delete all chirp-related blocks and ensembles in the 'Pulse Generator' GUI. This error would never show up.

**Comment by Neverhorst** [comment]
@liuyanulm:
Sorry for replying so late. This issue is known and is coming from _yaml_ not being able to cope with a `frozenset` type `StatusVar`.
This will be fixed once PR #542 is merged into master.
But it has nothing to do with this particular branch.

**Comment by liuyanulm** [comment]
> @liuyanulm:
> Sorry for replying so late. This issue is known and is coming from _yaml_ not being able to cope with a `frozenset` type `StatusVar`.
> This will be fixed once PR #542 is merged into master.
> But it has nothing to do with this particular branch.

Cool! Thanks!

**Comment by Neverhorst** [comment]
So this PR is lingering for quite some time... 

> Cool addition.
> 
> Only thing is the helper methods (starting with underscore, e.g. _get_mw_element_linearchirp) belong in the base class PredefinedGeneratorBase so you can use them in your custom predefined methods as well.

**Comment by jochen-scheuer** [comment]
I did the requested change and tested it on dummy. Seems to work fine.

**Comment by jochen-scheuer** [comment]
I did the from pycharm suggested code style suggestions and I tested both sequences in the dummy.

**Pull request merged**
