### PR TITLE
Save additional parameters

### PR DESCRIPTION
**Pull request by alrik-durand**
## Description
I've added functions in save logic to add additional parameters
Also modified counter and pulsed modules to be able to not save everything if not needed.

## Motivation and Context
When using Jupyter notebooks or tasks to save data, having additional parameters is quite usefull

## How Has This Been Tested?
This have been tested on dummies
I've checked that the default behavious has not changed.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by kay-jahnke** [comment]
@kay-jahnke @drogenlied @Neverhorst : please test

**Comment by Neverhorst** [comment]
@kay-jahnke: close != comment

**Comment by alrik-durand** [comment]
I've added a small fix for rpyc problems, this should be it !

**Comment by kay-jahnke** [comment]
Tested it on Win7 64x dummy:
- The additional parameters work fine for me. 
- Not sure about the changes to the pulsed figures however. Someone who used them more often should comment here.

Once this PR is through I will put up another PR to handle the POIs with the additional parameters.

**Comment by alrik-durand** [comment]
You are right, I've changed the code as suggested !

**Comment by Neverhorst** [comment]
Ok, thanks. That looks good now.

I just realized another issue:
If you change the method signature of `PulsedMeasurementLogic.save_measurement_data` you should also change it in the same way in `PulsedMasterLogic.save_measurement_data` since this is the dedicated interface logic to control the entire pulsed toolbox.
If you could add this small change please, we can finally merge this PR.

After merging I will open a new PR to make `PoiManagerLogic` use this feature.

**Comment by alrik-durand** [comment]
Done !

**Pull request merged**
