### PR TITLE
Rpyc / Remote server optional

### PR DESCRIPTION
**Pull request by tobiasgehring**
So far rpyc was a core dependency and an rpyc server was always started even if the functionality wasn't used at all. This patch makes both optional. 

## Description
Using a remote module is a nice feature in qudi, however, not quite everybody is using it. Up to now rpyc had to be installed and a server was started even if the functionality wasn't used at all. This patch disables all remote module functionality if rpyc is not installed. If it is installed qudi can be used as client or as server or both, depending on configuration.

The server is now disabled if no corresponding configuration is available. This can in principle break existing configurations (though I hope that people using the functionality use certificates!).
New configuration options:
```
[global]
module_server:
  address: ''
  port: 12345
  certfile: 'filename.cert'
  keyfile: 'filename.key'
```
The old configuration options still work and are labelled as deprecated. The reason for the change is that I prefer to have them grouped together.

Note: This patch does not intend to fix any issues within the remote module implementation.

## How Has This Been Tested?
I tried the different configurations (server, client, both) including an uninstalled rpyc.

Would be great if someone actually using the functionality could check that it is still working as expected.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.
No documentation describing the remote module functionality exists yet.

### CODE REVIEW

**Comment by drogenlied** [comment]
Apart from the missing documentation and the
`Remote module sharing does not work as server startup failed earlier, check your log.`
error that needs to be rephrased this is ok.

**Comment by tobiasgehring** [comment]
- added documentation
- changed error message

**Comment by tobiasgehring** [comment]
will you merge it? I'm not authorized to do this.

**Comment by drogenlied** [comment]
Strange, the permissions in the interface are the same for you and the qudi-committers group.

**Pull request merged**
