### PR TITLE
Pulsed timetrace analysis

### PR DESCRIPTION
**Pull request by alrik-durand**
## Description
I've added a new tab to pulsed measurement, with features to plot and analyse the timetrace directly.
I've also added checkboxes to save selectively pulses extracted data or timetrace data, to give access to this feature pre-existing in logic.
I have also created a utils/curve_methods with general function I needed and believe to be more general than this module. I was hoping to start a kind of library for function used generally in data analysis of Qudi's files, but this may need it's own thread.

## Motivation and Context
Pulsed measurement is very useful to extract spin state information out of pulses, but lacked features to just analyse the timetrace, giving helpful information on the rise or fall times of pulses, extracting lifetimes or other features of time resolved experiments.

## How Has This Been Tested?
I've tested this with dummy modules, I've been as careful as possible to not break any pre-existing behavior of the pulsed module. I've checked that it work as I intend on my personal linux machine.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

I've ticked breaking change as I'm worried the *do_fit* and related functions have a slightly different prototype, with a string instead of a boolean. Other than that it should work fine.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by Neverhorst** [comment]
As much as I can understand the temptation to turn the pulsed measurement "thingy" into a general purpose data playground, I must opt against this PR.
Current pulsed measurement is already way too bloated and in-transparent.

The idea of qudi as a project is to provide a highly modular(!) framework and library for scientists to use and tailor to their needs even without advanced programming knowledge. So one important key feature is simplicity and readability of code for experimentation modules.
Pulsed measurement as a toolbox is straining this principle quite heavily already and should be divided into more logic modules.
So you should only improve/expand existing experimentation (logic) modules if it helps them perform their intended task better.
For a new class of experiments (like analyzing time trace data in a totally different way for e.g. single shot readout) it is mandatory to write a new logic module.
If you can re-use some features from pulsed measurement (like `SequenceGeneratorLogic`) it is perfectly fine to connect to these modules.

The overhead of writing new modules is quite small.

If people want to discuss this issue further, please feel free to do so here (and re-open PR if necessary).

**Comment by alrik-durand** [comment]
I would indeed like to discuss this.
But first thank you for your feedbacks.

I've been frustrated many time by the impossibility to save an image of the raw timetrace from pulsed measurement. That is why I think it helps perform the intended task better. 
I understand your point about the complexity of pulsed measurement, but in fact I would say maybe the time trace analysis should have been part of the "basic package" and complex sequences analysis/pulse extraction should be constructed on top of it, in another module ?

I have to admin I would like this to be merged, but I'm open for constructive discussions :)

**Comment by Neverhorst** [comment]
Ok let's see:

- saving image files of data graphs was only ever intended as "thumbnail" for the measurement outcome. If you want to use qudi as plotting front-end for publication/presentation, please write your own plotting module. You can also have a look at `gui.simpledatagui`.
There are at least as many opinions about how data plots should look like as there are researchers using qudi.
In fact most complaints I receive about saving data in qudi originates from spamming image files all over the place by default which also reduces the data save performance by a factor of up to 100.
That is why there are tendencies to reduce the places where images are created.
If you just want some snapshot image of (a zoom-in of) the raw time trace you can use the plot in the "pulse extraction" tab and export an image with the right-click context menu (as with almost any plot).

- One of the reasons why pulsed measurement is such a complex module is the capability to dynamically add raw data processing extensions. They are called extraction methods and analysis methods. 
For extraction methods you can simply drop in a "black box function" that takes any number of user inputs (automatically generated in GUI) as well as the raw time trace and returns a 2D numpy array containing basically anything.
For analysis methods you can do something similar by taking previously mentioned 2D array and returning data points shown in the analysis tab.
Refer to `how_to_add_extraction_methods` and `how_to_add_analysis_methods` in documentation.
This feature is very flexible so if you can not use it for your pulsed measurement data analysis purposes, this is most likely the wrong module for your experiment.

- If the above feature can not help you, then you literally just need the `SequenceGeneratorLogic` and a raw time trace from a counting device (both available in qudi as separate modules) and write some custom logic to process that data in the way you like.

**Comment by alrik-durand** [comment]
Thank you again for all your advises. It may seems simple to you but it's really helpful to me !

I like you idea of using extraction and analysis methods to do the same thing, I have never looked in detail at this part of Qudi so I didn't even think to look into that. I will for sure. 

I'll try to do it this way and maybe submit it in another PR (it still may be useful to someone else)

Case closed !

**Pull request closed without merging**
