### PR TITLE
auto_catch_poi functionality

### PR DESCRIPTION
**Pull request by liuyanulm**
POI auto catch functionality is added.
## Description

The function added in the end of poi_manager_logic.py, can add many POIs in a blink of eyes... But in case of naming/tagging conflicts, a delay of 0.2 s isto be carried on purpose after each POI is added.

NOTE:
A filter depending on the general optical diffraction limit is within the architecture of  the functionality, it changes in accordance with scanning step size.
A descent confocal image is necessary for this... The ones with crappy resolution (i.e. pixel_step of 1 um), would not be good, you will suffer multi poi_selections in a single emitter.
Nevertheless, if few emitters you want to add but the function does not select them as POIs, you can add them by hand. On the hand, you can delete some POIs you don't want as well.

## Motivation and Context

In the cases where you need to select good emitters by ODMR or spectra, etc... 
This functionality helps you to select many POIs efficiently and accurately.
By the way, I wonder if it is necessary to add a button in the poiGUI...

## How Has This Been Tested?

tested on Win 10, runing with dummy data.
## Screenshots (only if appropriate, delete if not):

poi_autocatch

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [x] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by liuyanulm** [comment]
This is a CALL for TEST.
I have also tested on Setup 5, with different scan shapes, and certain background noise. And it is still a powerful tool, when the s/n threshold became tunable.



@drogenlied @Neverhorst 
Please take 5 minutes for a review.

**Comment by diamond2nv** [comment]
@liuyanulm 
should merge into "omniscan working branch" instead of "master"
ref: https://github.com/Ulm-IQO/qudi/pull/493

"Approval on the other PRs that should be merged here but not into master needs to be done in the comments."

- [ ] maybe need a double check for "del all POIs" 

- [ ] Is there a possibility to store POIs' info into SQLite, for future export use ( scikit-learn ...)

**Comment by Neverhorst** [comment]
@diamond2nv: See my comments for PR #506. If you want to request features, please open an issue. Possible improvements regarding anything else than a POI auto-find functionality must be handled in a separate branch/PR.

> @liuyanulm
> should merge into "omniscan working branch" instead of "master"
> ref: #493
> 
> "Approval on the other PRs that should be merged here but not into master needs to be done in the comments."
> 
> * [ ]  maybe need a double check for "del all POIs"
> * [ ]  Is there a possibility to store POIs' info into SQLite, for future export use ( scikit-learn ...)

**Comment by diamond2nv** [comment]
- ref : https://github.com/Ulm-IQO/qudi/issues/496

```python
# Global threshold
global_thresh = skif.threshold_otsu(img)
#global_thresh = 0.5
```

- This is the threshold of float_count_value.

```python
#Coordinates and filters
lm = morph.local_maxima(img)
```

- This is the threshold of pixel value, most nearby (local_maxima(img) of xy scan image)

- When scan step size is large, global threshold of count value will became large?

and the threshold of pixel most nearby (of xy scan image) will became large too.

**Comment by diamond2nv** [comment]
- ref: https://github.com/Ulm-IQO/qudi/issues/507

> branch : POI_autocatch: "Auto Catch" will cause non-stopable behave.

>  nedd adding some kind of interface.local_maxima for "logic\poi_manager_logic.py" and "logic\auto_catch_logic.py"(need to be added, too)
    * interface.local_maxima tack in confocal image from "poi_manager_logic.py" to "auto_catch_logic.py":
        * var: ndarry.scan_image( x_pixels_int, y_pixels_int, count_value_float), 
        * scanning_step_size_float_(m), 
        * tag_string, (like: "poi_20190430_auto")
        * and maybe a tunable s/n threshold for manual intervention;
        * and maybe a bash_string, (8 random chars) to istinguish the task/measurement for future use(like to do auto-catch by deep learning...***exchanging data in Redis***)
    * "auto_catch_logic.py" using "import skimage.morphology.local_maxima()" to auto discover all fluorescent spots in the ndarry.scan_image,  ***this method used a lot in tracking stars in astronomy*** .
        * return (x_pixels_int, y_pixels_int, lim_threshold_float, poi_auto_name_full_string)
             * poi_auto_name_full_string: like "poi_20190430_auto_b0sh3fohls"
    * interface.local_maxima tack auto-cath_xy info from "auto_catch_logic.py" to "poi_manager_logic.py".

**Comment by liuyanulm** [comment]
> * ref: #507
> 
> > branch : POI_autocatch: "Auto Catch" will cause non-stopable behave.
> 
> * naming/tagging POIs use python uuid module canbe faster
> * need adding some kind of interface.local_maxima for "logic\poi_manager_logic.py" and "logic\auto_catch_logic.py"(need to be added, too)
>   
>   * interface.local_maxima tack in confocal image from "poi_manager_logic.py" to "auto_catch_logic.py":
>     
>     * var: ndarry.scan_image( x_pixels_int, y_pixels_int, count_value_float),
>     * var: scan range x y , resolution(steps)
>     * ~scanning_step_size_float_(m)~
>     * tag_string, (like: "poi_20190430_auto")
>     * and maybe a tunable s/n threshold for manual intervention;
>     * and maybe a hash_string, (8 random chars) to istinguish the task/measurement for future use(like to do auto-catch by **deep learning** ..._**exchanging data in Redis**_)
>       
>       * future: Object recognition，Auto Calibration，Building navigation maps for the sample...
>   * "auto_catch_logic.py" using "import skimage.morphology.local_maxima()" to auto discover all fluorescent spots in the ndarry.scan_image,  _**this method used a lot in tracking stars in astronomy**_ .
>     
>     * return (x_pixels_float, y_pixels_float)
>     * return brightness_global_threshold_float
>     * return pixels_most_nearby_threshold_float
>     * return the task hash_string (not needed with no Redis)
>     * return poi_auto_name_full_string(+ _**uuid**_ )
>       
>       * poi_auto_name_full_string: like "poi_20190430_auto_000...001"
>   * interface.local_maxima tack auto-cath_xy info from "auto_catch_logic.py" to "poi_manager_logic.py".

@diamond2nv Hi! Thanks for presenting your ideas enthusiastically here. Before any further inputs, please be aware of some strategies of the Qudi development.
Qudi is a complex module, also with importing a lot of packages. Nevertheless, we are careful with usages of new packages which may have considerable risks of maintenance breakups. We prefer to use packages with histories of reliability, with strong backup teams, such as numpy, matplotlib, etc.. Unless the functionalities of a new package are uniquely necessary, we would not use it. i.e. That is why I coded the auto_find function series in order not to use the skimage module which you have suggested.
And secondly, usually in the Qudi development, if you would like to add some new features with very little changes, you should create your local branch and code independently, and then commit it to the master.  Then the administrators would review your change, and see the necessity of pushing it to the master. simply bringing up an issue with merely an idea and then leaving it there generally would only cause confusions to the developing team. I kindly wish you would understand this.
Cheers,
Yan Liu

**Comment by diamond2nv** [comment]
Thanks, learned a lot.

**Comment by liuyanulm** [comment]
@Neverhorst 

- The poi_threshold property needs an update signal from logic to GUI so that the GUI is updated upon a programmatic change in logic. (emit signal from inside set_poi_threshold)
I am not very clear about what is required.

- What is threhold meaning exactly. I thought it would be the absolute mean brightness of a POI but you calculate it like threshold = scan_mean(scan_image) * self._poi_threshold? This is strange.
The threshold is considered as a brightness bar for determination of fluorescent area (brighter than overall background counts). It works quite well in here.

**Comment by liuyanulm** [comment]
Oh, it is actually reported in #515

**Comment by Neverhorst** [comment]
Ok, so during testing I could not use this functionality in a single case. 
My scans of very shallow NVs (with charge state instabilities) usually do not look as nice as in the screenshots. The mean background is about 10-20kcts and the NVs about 90kcts but the algorithm seems to find a huge number of false hits.
If you want to play around with my data, you can load the ROI attached:
[ROI.zip](https://github.com/Ulm-IQO/qudi/files/3261369/ROI.zip)

**Comment by liuyanulm** [comment]
> Ok, so during testing I could not use this functionality in a single case.
> My scans of very shallow NVs (with charge state instabilities) usually do not look as nice as in the screenshots. The mean background is about 10-20kcts and the NVs about 90kcts but the algorithm seems to find a huge number of false hits.
> If you want to play around with my data, you can load the ROI attached:
> [ROI.zip](https://github.com/Ulm-IQO/qudi/files/3261369/ROI.zip)

OK, I would definitely try some different POI parameters to find the problem.
which directory should I copy the confocal.npy to so Qudi would load the confocal scan?

**Comment by Neverhorst** [comment]
I played around with the parameters. 
It doesn't matter where you put the two files. You can load them with the loading dialog in the POI manager Gui.

**Comment by liuyanulm** [comment]
> I played around with the parameters.
> It doesn't matter where you put the two files. You can load them with the loading dialog in the POI manager Gui.

I am back online now.
I simply uploaded your roi file, see the image as below.
image

I guess this the result of your playing around with the parameters.
It looks to me that this catch is not bad.

Nevertheless, when I played with the S/N, using 3.5 as example, the blinking of background counts does cause miselection of pois. I guess that is what your call 'falsehits'? 

This roi is the case of many blinking situation. This bug is totally fixable to me. I will add a 'smoothen button' to remove the isolated blinking pixels.

Thanks for the test.

**Comment by Neverhorst** [comment]
Nope, the POIs in the example are selected by hand.
The blinking is quite normal for most samples. (It's a very fine resolved image)
But from what I understood the size parameter should exclude single pixel recognition.

**Comment by liuyanulm** [comment]
> Nope, the POIs in the example are selected by hand.
> The blinking is quite normal for most samples. (It's a very fine resolved image)
> But from what I understood the size parameter should exclude single pixel recognition.

Indeed.
I have come up with a quick fix, by adding an average intensity control during the local_max selection.
image

**Comment by liuyanulm** [comment]
For now, this auto_poi works much better I think.
see the parameters and results as below:
image

**Comment by Neverhorst** [comment]
I have added some improvements for the GUI layout and fixed a recently introduced bug.

It's much better now after your last revision, @liuyanulm. But when using this functionality with low resolution, the found POI position is off by about one pixel:
screenshot_misplaced
I guess this comes from the way images are drawn in Qt. Should be easily fixable by a simple coordinate transformation.

Also the POI size constraint ("POI Diameter") does not seem to avoid selecting the same colorcenter multiple times. In the following image the diameter was set to 2 microns (with a scan resolution of 1 micron), yet it selected the same spot multiple times with a distance <2 microns:
screenshot_doublehit

Both examples can be reproduced using the dummy scanner module.

**Pull request merged**
