### PR TITLE
Revert "Made natural_sort helper function more robust"

### PR DESCRIPTION
**Pull request by Neverhorst**
Reverts Ulm-IQO/qudi#533 due to hastily introduced errors

### CODE REVIEW

**Comment by kay-jahnke** [comment]
How about the upgraded fix?

I agree, the usage of the natural_sort on non-string objects is the problem, but I would like the helper to be more robust and actually somehow cope with that.

**Comment by Neverhorst** [comment]
Shame! _\*dingdingding*_ Shame! _\*dingding*_ Shame!

I agree with @drogenlied. We should never do such a search and replace rampage again without thorough testing.

However I just thought about the same thing @kay-jahnke just committed. I think this is the best solution. (Would be even better to use explicit exceptions)

**Comment by kay-jahnke** [comment]
@alastair-marshall and @alrik-durand :
Could you please test this case for your  setup?

**Comment by alrik-durand** [comment]
No more problem here !

**Comment by Neverhorst** [comment]
I think the fix by @kay-jahnke is pretty much bulletproof since it truly falls back to `sorted()` upon a somehow failed natural sorting. This should basically undo all the damage done by replacing all occurrences of `sorted` with `natural_sort`.

Can we all agree on merging this?

**Comment by alrik-durand** [comment]
Yes please !

**Pull request merged**
