### PR TITLE
Power supply Keysight E3631A hardware file

### PR DESCRIPTION
**Pull request by alrik-durand**
## Description
I've added a hardware file to interface a power supply Keysight E3631A.

## Motivation and Context
This change add support to new instrument throught the Qudi ProcessControlInterface.

## How Has This Been Tested?
I've used this on the instrument with a Windows 10 PC.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by Neverhorst** [comment]
I see no problem in adding a new hardware module.

I have a request, though... Could you please change all method names (search and replace for all modules) related to the `ProcessControlInterface` and `ProcessInterface` to qudi naming convention?
It just occurred to me that these interfaces use _CamelCase_ convention but for qudi we decided all method names should be lower case and words separated by underscores.
This should be done as soon as possible before more people write modules based on these interfaces.

**Comment by alrik-durand** [comment]
Thank you for you answer.
As you have mentionned [before ](https://github.com/Ulm-IQO/qudi/pull/468), a change in an interface should not be done slightly, so I kept the old naming convention for these PR. 
I agree this need to be done anyway, maybe I can do it right away in a separate PR ?

**Comment by Neverhorst** [comment]
Yes, I said that. ;)
But in case of the `Process(Control)Interface` I would sneak this change in as early as possible because it is not (barely) being used so far.
A separate PR is also fine, thank you.

**Comment by Neverhorst** [comment]
Could you please resolve the `changelog.md` conflict?

**Comment by alrik-durand** [comment]
This should do it !

**Pull request merged**
