### PR TITLE
Fastcomtec 7889 & DMA mode

### PR DESCRIPTION
**Pull request by alrik-durand**
## Description
This PR adds compatibility with fastcomtec model 7889 through a config option in 7887 hardware file. 
This PR also adds the option to set DMA mode to true by default with another config option.
Finally, get_current_sweeps now uses the start number and not the sweep numbers.

## Motivation and Context
1. It's nice when you have a 7889 card.
2. 7889 model have been seen to miss some triggers when not in DMA mode.
3. Also when it does, the number of start and sweeps become different, for a reason still unclear to me. Maybe I'm wrong but from my test, it seem the relevant number is the start number.
The only reason I'm using the sweep number is to normalize the timetrace to get counts per second that matches the slow counter. When *starts* and *sweeps* differ, the start number is the one that produce an count per second that matches slow counter.

## How Has This Been Tested?
I've tested this on 7889. I have not tested this on a 7887 but there should not be any change for it.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by kay-jahnke** [comment]
This PR looks fine to me but someone should please test it on a Fastcomtec 7887 hardware.
@Neverhorst @SimonSchmitt88 @timoML @MathiasMetsch @Yawghmoth Do any of you have the 7887 and could test please.

**Comment by Neverhorst** [comment]
I don't have one and never had one either.

**Comment by timoML** [comment]
Tested on setup3 with p7887. Runs Rabi as expected.

**Review by Neverhorst — APPROVED** [review]
Since this PR has been open for quite some time, I think we won't get more tests from people with FastComTec hardware. Thank you, @timoML for testing. I think we should merge.

**Pull request merged**
