### PR TITLE
Added ScienDSpinbox compatibility to mapper

### PR DESCRIPTION
**Pull request by alrik-durand**
## Description
I have added the compatibility of SiencDSpinbox and mapper.

Also this PR brings the documentation update from PR #587 which is now a bit obsolete.

## Motivation and Context
Mapper module helps develop GUI modules by taking care of the repetitive task of mapping the state of the model to the state of the view in the GUI. It is still not used very much.
ScienDSpinbox it an layer on top of Qt Spinbox to help deals with Scientific unit. It is used in most of the spinbox of Qudi. 
Compatibility between the two was missing, this small PR adds such support.

## How Has This Been Tested?
This PR has been tested with code from a PID overhaul that will be included in another PR.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have documented my changes in the changelog (`documentation/changelog.md`)
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added/updated for the module the config example in the docstring of the class accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [x] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by tobiasgehring** [comment]
This is one option. Another option, which may only require minimal changes, is to edit the spinbox itself and add
`value_float = QtCore.Property(float, fget=value, fset=setValue, notify=valueChanged)`
With this qt property we just need to add two lines around line 130 in mapper to return `value_float` if instance is the scientific spinbox.
I think this solution would be more elegant.

**Comment by tobiasgehring** [comment]
see #593

**Comment by alrik-durand** [comment]
I agree with both of you that Option 1 is cleaner. Thank you.
I'm not very familiar with the GUI side of Qudi so I sometimes try unnecessary complicated options !

I implemented the changes mentioned and tested it on a branch using mapper ad ScienDSpinbox for a pid_overlaul, it works perfectly.

Should I change anything else ?

**Comment by Neverhorst** [comment]
Um... should the mapper at line 130 not return `value_float` (instead of `value`)?

**Comment by alrik-durand** [comment]
You are totally right... I tested it while specifying the *widget_property_name* the GUI but this is obviously better. Fixed.

**Comment by Neverhorst** [comment]
OK cool. Would you also directly fix it for the `ScienSpinBox` (int) as well? Should be the same process with `value_int` instead.

**Comment by alrik-durand** [comment]
No problem ! I've changed it.

**Review by Neverhorst — APPROVED** [review]

**Pull request merged**
