### PR TITLE
Simplifying Modules

### PR DESCRIPTION
**Pull request by tobiasgehring**
This patch simplifies modules by nesting the fysom state machine instead of subclassing it.

## Description
Instead of subclassing fysom it is now nested and the state machine is accessible by the attribute module_state. To get the current state you can either use module_state.current (Fysom standard) or module_state as callable: module_state().
Some methods in the module base class like get_home_dir and get_main_dir have been moved to core.util.modules, others have been deprecated and assigned a warning.

## Motivation and Context
The fysom state machine includes many dynamically added attributes and methods and it happens quite often that one overrides a methods without noticing. Examples are run, stop, trigger, lock and unlock.

## How Has This Been Tested?
I started qudi and a couple of modules. However this pull request includes changes to many modules so I would appreciate if someone can test some more modules. I haven't used "Load all modules" on default configuration yet since for some reason my python installation causes qudi to raise errors (pandas has some issues).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have checked that the change does not contain obvious errors (syntax, indentation, mutable default values).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration with my changes included.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

### CODE REVIEW

**Comment by drogenlied** [comment]
I have no issues with this on my Debian PC at home.

Can anybody comment if their custom notebooks use `getState`?

**Comment by Neverhorst** [comment]
Yes, my notebooks for pulsed experiments use getState. But that shouldn't be a problem to change.

**Comment by tobiasgehring** [comment]
could you approve the pull request?

**Comment by tobiasgehring** [comment]
thanks. Unfortunately I'm not authorized to merge it. I believe this is because I'm outside collaborator and the master branch is protected.

**Comment by Neverhorst** [comment]
Hey I'm back from the holidays now.
Looks good also from my side, thank you. I will merge it. 
Could you please write an email over the announce list with the important changes that could break peoples scripts etc. (like using `getState`)?

**Pull request merged**
